# Generated by Django 3.1.2 on 2020-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201014_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('date', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('role', models.CharField(max_length=120)),
                ('institution', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
